// GetFolderDescription, ported: a pre-indexed, annotated repo tree that answers
// "what is where" in hundreds of tokens instead of an exploration spree.
// Fully deterministic — heuristic annotations, no model calls, mtime-keyed cache.
import { readdirSync, readFileSync, statSync, existsSync, writeFileSync, mkdirSync } from "node:fs";
import { join, extname, basename } from "node:path";
import { yeschefHome, projectSlug, WALK_IGNORE, WALK_DOT_ALLOW } from "./core.js";

interface DirSummary {
  path: string;
  files: number;
  dirs: number;
  exts: Record<string, number>;
  note: string;
  keyFiles: string[];
}

const KEY_FILES = /^(package\.json|pyproject\.toml|setup\.py|cargo\.toml|go\.mod|pom\.xml|build\.gradle|.*\.csproj|.*\.sln|makefile|dockerfile|docker-compose\.ya?ml|readme\.md|claude\.md|index\.[tj]sx?|main\.[a-z]+|app\.[a-z]+|__init__\.py|mod\.rs|schema\.(sql|prisma|graphql))$/i;

function annotate(dir: string, entries: string[]): string {
  const notes: string[] = [];
  if (entries.some((e) => /^package\.json$/i.test(e))) {
    try {
      const pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
      if (pkg.name) notes.push(`npm:${pkg.name}`);
      if (pkg.description) notes.push(String(pkg.description).slice(0, 70));
    } catch { /* unreadable */ }
  } else if (entries.some((e) => /^readme\.md$/i.test(e))) {
    try {
      const first = readFileSync(join(dir, entries.find((e) => /^readme\.md$/i.test(e))!), "utf8")
        .split("\n").map((l) => l.replace(/^#+\s*/, "").trim()).find((l) => l.length > 8);
      if (first) notes.push(first.slice(0, 80));
    } catch { /* unreadable */ }
  }
  if (entries.some((e) => /(^|\.)(test|spec)s?\./i.test(e) || /^(tests?|__tests__|specs?)$/i.test(e))) notes.push("tests");
  return notes.join(" — ");
}

function walk(root: string, rel: string, depth: number, maxDepth: number, acc: DirSummary[], budget: { dirs: number }): void {
  if (depth > maxDepth || budget.dirs <= 0) return;
  const abs = join(root, rel);
  let entries: string[];
  try { entries = readdirSync(abs); } catch { return; }
  budget.dirs--;
  const sum: DirSummary = { path: rel || ".", files: 0, dirs: 0, exts: {}, note: "", keyFiles: [] };
  const subdirs: string[] = [];
  for (const e of entries) {
    if (e.startsWith(".") && !WALK_DOT_ALLOW.has(e)) continue;
    if (WALK_IGNORE.has(e)) continue;
    let st;
    try { st = statSync(join(abs, e)); } catch { continue; }
    if (st.isDirectory()) { sum.dirs++; subdirs.push(e); }
    else {
      sum.files++;
      const ext = extname(e).toLowerCase() || basename(e);
      sum.exts[ext] = (sum.exts[ext] ?? 0) + 1;
      if (KEY_FILES.test(e) && sum.keyFiles.length < 6) sum.keyFiles.push(e);
    }
  }
  sum.note = annotate(abs, entries);
  acc.push(sum);
  for (const d of subdirs) walk(root, rel ? `${rel}/${d}` : d, depth + 1, maxDepth, acc, budget);
}

export function buildFolderDescription(root: string, maxDepth = 3, maxChars = 4500): string {
  const acc: DirSummary[] = [];
  walk(root, "", 0, maxDepth, acc, { dirs: 400 });
  const lines: string[] = [`Folder description of ${root} (depth ${maxDepth}, generated by yeschef — cheap, trust it before exploring):`];
  for (const d of acc) {
    const ext = Object.entries(d.exts).sort((a, b) => b[1] - a[1]).slice(0, 4)
      .map(([e, n]) => `${n}${e.startsWith(".") ? e : " " + e}`).join(", ");
    const bits = [
      `${d.path}/`,
      `${d.files}f${d.dirs ? `,${d.dirs}d` : ""}`,
      ext,
      d.keyFiles.length ? `key: ${d.keyFiles.join(" ")}` : "",
      d.note,
    ].filter(Boolean);
    lines.push("  " + bits.join(" · "));
    if (lines.join("\n").length > maxChars) {
      lines.push(`  … ${acc.length - acc.indexOf(d)} more directories (raise depth/maxChars or target a subpath)`);
      break;
    }
  }
  return lines.join("\n");
}

interface CacheEntry { builtAt: number; rootMtime: number; text: string; depth: number }

function cachePath(root: string, depth: number): string {
  const dir = join(yeschefHome(), "cache");
  mkdirSync(dir, { recursive: true });
  // depth in the filename: session-start (depth 2) and folder_desc (depth 3)
  // alternated on a single slot, each invalidating the other's cache.
  return join(dir, `folderdesc-${projectSlug(root)}-d${depth}.json`);
}

/** Cached description; invalidated when the root dir's mtime changes or after 10 min. */
export function getFolderDescription(root: string, depth = 3, refresh = false): string {
  const p = cachePath(root, depth);
  let rootMtime = 0;
  try { rootMtime = statSync(root).mtimeMs; } catch { /* keep 0 */ }
  if (!refresh && existsSync(p)) {
    try {
      const c: CacheEntry = JSON.parse(readFileSync(p, "utf8"));
      if (c.depth === depth && c.rootMtime === rootMtime && Date.now() - c.builtAt < 600000) return c.text;
    } catch { /* rebuild */ }
  }
  const text = buildFolderDescription(root, depth);
  try { writeFileSync(p, JSON.stringify({ builtAt: Date.now(), rootMtime, text, depth } satisfies CacheEntry)); } catch { /* best effort */ }
  return text;
}
